### ISSUE TITLE
Crash occuring with some collisions

### ISSUE THREAD

**Issue by kevin-dorange** [NebulaTales/bevy_asteroids#2]
For some reason, the game crashes with an "non existing entity" message when some collision appear.

It's not easy to reproduce as it happens only a few time. 
I suspect the crash happens during an entity despawn. We're trying to despawn something already gone.

**Comment by kevin-dorange** [comment]
```
thread 'main' panicked at 'Entity does not exist', /home/oragon/.cargo/git/checkouts/bevy-f7ffde730c324c74/653c103/crates/bevy_ecs/src/world/mod.rs:214:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
   3: <bevy_ecs::system::commands::Insert<T> as bevy_ecs::system::commands::Command>::write
   4: bevy_ecs::system::commands::CommandQueue::apply
   5: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
   6: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
   7: bevy_winit::winit_runner_with::{{closure}}
   8: winit::platform_impl::platform::x11::EventLoop<T>::run_return
   9: winit::platform_impl::platform::x11::EventLoop<T>::run
  10: winit::platform_impl::platform::EventLoop<T>::run
  11: winit::event_loop::EventLoop<T>::run
  12: bevy_winit::run
  13: bevy_winit::winit_runner_with
  14: core::ops::function::Fn::call
  15: bevy_app::app_builder::AppBuilder::run
  16: asteroids::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: Job 1, 'RUST_BACKTRACE=1 cargo run --re…' terminated by signal SIGSEGV (Address boundary error)
```
